# =============================================================================
# 2D Sedov-like blast wave with gas self-gravity feedback
# =============================================================================
# Physics:
#   Conserved variables U = [rho, rho*u, rho*v, E]
#   Euler equations with optional gravitational source terms:
#       dU/dt + dF/dx + dG/dy = S_grav
#
# Numerical method:
#   Time integration        : RK4
#   Spatial reconstruction  : PLM reconstruction on primitive variables (Modified from PPM)
#   Interface flux          : HLLC approximate Riemann solver / Rusanov Riemann solver
#   Boundary condition      : periodic for hydrodynamics
#   Gravity                 : periodic FFT Poisson solver sourced by rho-rho_mean
#
# Important modeling choice:
#   This is a Sedov-like setup: the shock is generated by central ENERGY
#   injection, not by imposing the shock radius by hand.
#   The Sedov-Taylor radius is used only as a diagnostic/reference:
#       R_s(t) ~ xi * (E0*t^2/rho0)^(1/(d+2))
#   In 2D: R_s(t) ~ xi * (E0*t^2/rho0)^(1/4)
# =============================================================================

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, PillowWriter
import os
from datetime import datetime

# =============================================================================
# Parameters
# =============================================================================
Lx = 1.0
Ly = 1.0
Nx_In = 128
Ny_In = 128
nghost = 3

gamma = 5.0 / 3.0
cfl = 0.35
end_time = 0.1
## critical 0.15
output_interval = 0.0025

# Sedov-like initial condition
rho0 = 1.0         # uniform ambient pre-shock density
P_amb = 1.0e-5      # ambient pressure
E0 = 1.0            # injected thermal energy per unit length in 2D
r_blast = 0.03      # radius of central energy injection region

# Self-gravity switch
# True means shock-compressed density sources Phi through Poisson equation.
USE_SELF_GRAVITY = True
SOLVER = 'Rusanov' # 'HLLC' for original HLLC Riemann solver, 'Rusanov' for Rusanov Riemann solver
Ggrav = 5.0        # gravitational constant in code units; increase carefully

# Numerical floors
rho_floor = 1.0e-12
P_floor = 1.0e-12

# Derived grid constants
Nx = Nx_In + 2 * nghost
Ny = Ny_In + 2 * nghost
dx = Lx / Nx_In
dy = Ly / Ny_In

x_real = (np.arange(Nx_In) + 0.5) * dx - 0.5 * Lx
y_real = (np.arange(Ny_In) + 0.5) * dy - 0.5 * Ly
X_real, Y_real = np.meshgrid(x_real, y_real, indexing="ij")
R_real = np.sqrt(X_real**2 + Y_real**2)

# =============================================================================
# Basic variable conversion
# =============================================================================
def compute_pressure(U):
    rho = np.maximum(U[..., 0], rho_floor)
    mx = U[..., 1]
    my = U[..., 2]
    E = U[..., 3]
    kinetic = 0.5 * (mx**2 + my**2) / rho
    P = (gamma - 1.0) * (E - kinetic)
    return np.maximum(P, P_floor)


def conserved_to_primitive(U):
    W = np.empty_like(U)
    rho = np.maximum(U[..., 0], rho_floor)
    P = compute_pressure(U)
    W[..., 0] = rho
    W[..., 1] = U[..., 1] / rho
    W[..., 2] = U[..., 2] / rho
    W[..., 3] = P
    return W


def primitive_to_conserved(W):
    U = np.empty_like(W)
    rho = np.maximum(W[..., 0], rho_floor)
    u = W[..., 1]
    v = W[..., 2]
    P = np.maximum(W[..., 3], P_floor)
    U[..., 0] = rho
    U[..., 1] = rho * u
    U[..., 2] = rho * v
    U[..., 3] = P / (gamma - 1.0) + 0.5 * rho * (u*u + v*v)
    return U


def apply_floors(U):
    U[..., 0] = np.maximum(U[..., 0], rho_floor)
    W = conserved_to_primitive(U)
    W[..., 0] = np.maximum(W[..., 0], rho_floor)
    W[..., 3] = np.maximum(W[..., 3], P_floor)
    return primitive_to_conserved(W)

# =============================================================================
# Boundary condition
# =============================================================================
def apply_periodic_boundary(U):
    # x direction
    U[:nghost, :, :] = U[Nx-2*nghost:Nx-nghost, :, :]
    U[Nx-nghost:, :, :] = U[nghost:2*nghost, :, :]

    # y direction
    U[:, :nghost, :] = U[:, Ny-2*nghost:Ny-nghost, :]
    U[:, Ny-nghost:, :] = U[:, nghost:2*nghost, :]

# =============================================================================
# Fluxes
# =============================================================================
def flux_x(U):
    W = conserved_to_primitive(U)
    rho, u, v, P = W[..., 0], W[..., 1], W[..., 2], W[..., 3]
    F = np.empty_like(U)
    F[..., 0] = rho * u
    F[..., 1] = rho * u*u + P
    F[..., 2] = rho * u*v
    F[..., 3] = (U[..., 3] + P) * u
    return F


def flux_y(U):
    W = conserved_to_primitive(U)
    rho, u, v, P = W[..., 0], W[..., 1], W[..., 2], W[..., 3]
    G = np.empty_like(U)
    G[..., 0] = rho * v
    G[..., 1] = rho * u*v
    G[..., 2] = rho * v*v + P
    G[..., 3] = (U[..., 3] + P) * v
    return G


def rusanov_flux_x(UL, UR):
    WL = conserved_to_primitive(UL)
    WR = conserved_to_primitive(UR)
    cL = np.sqrt(gamma * WL[..., 3] / WL[..., 0])
    cR = np.sqrt(gamma * WR[..., 3] / WR[..., 0])
    a = np.maximum(np.abs(WL[..., 1]) + cL, np.abs(WR[..., 1]) + cR)
    return 0.5 * (flux_x(UL) + flux_x(UR)) - 0.5 * a[..., None] * (UR - UL)


def rusanov_flux_y(UL, UR):
    WL = conserved_to_primitive(UL)
    WR = conserved_to_primitive(UR)
    cL = np.sqrt(gamma * WL[..., 3] / WL[..., 0])
    cR = np.sqrt(gamma * WR[..., 3] / WR[..., 0])
    a = np.maximum(np.abs(WL[..., 2]) + cL, np.abs(WR[..., 2]) + cR)
    return 0.5 * (flux_y(UL) + flux_y(UR)) - 0.5 * a[..., None] * (UR - UL)


# =============================================================================
# HLLC approximate Riemann solver
# =============================================================================
def _hllc_flux_normal(UL, UR, direction="x"):
    """Vectorized HLLC flux for the Euler equations."""
    WL = conserved_to_primitive(UL)
    WR = conserved_to_primitive(UR)

    rhoL = np.maximum(WL[..., 0], rho_floor)
    rhoR = np.maximum(WR[..., 0], rho_floor)
    uL, vL, pL = WL[..., 1], WL[..., 2], np.maximum(WL[..., 3], P_floor)
    uR, vR, pR = WR[..., 1], WR[..., 2], np.maximum(WR[..., 3], P_floor)

    if direction == "x":
        unL, utL = uL, vL
        unR, utR = uR, vR
        FL = flux_x(UL)
        FR = flux_x(UR)
    elif direction == "y":
        unL, utL = vL, uL
        unR, utR = vR, uR
        FL = flux_y(UL)
        FR = flux_y(UR)
    else:
        raise ValueError("direction must be 'x' or 'y'")

    cL = np.sqrt(gamma * pL / rhoL)
    cR = np.sqrt(gamma * pR / rhoR)

    # Davis wave-speed estimate. It is robust and works well as a first HLLC
    # replacement for Rusanov in strong-shock tests.
    SL = np.minimum(unL - cL, unR - cR)
    SR = np.maximum(unL + cL, unR + cR)

    denom = rhoL * (SL - unL) - rhoR * (SR - unR)
    denom = np.where(np.abs(denom) > 1.0e-30, denom, np.sign(denom + 1.0e-300) * 1.0e-30)
    SM = (
        pR - pL
        + rhoL * unL * (SL - unL)
        - rhoR * unR * (SR - unR)
    ) / denom

    pstarL = pL + rhoL * (SL - unL) * (SM - unL)
    pstarR = pR + rhoR * (SR - unR) * (SM - unR)
    pstar = np.maximum(0.5 * (pstarL + pstarR), P_floor)

    def star_state(U, rho, un, ut, p, S):
        factor = rho * (S - un) / np.where(
            np.abs(S - SM) > 1.0e-30,
            S - SM,
            np.sign(S - SM + 1.0e-300) * 1.0e-30,
        )

        Ustar = np.empty_like(U)
        Ustar[..., 0] = factor
        if direction == "x":
            Ustar[..., 1] = factor * SM
            Ustar[..., 2] = factor * ut
        else:
            Ustar[..., 1] = factor * ut
            Ustar[..., 2] = factor * SM

        Ustar[..., 3] = (
            (S - un) * U[..., 3]
            - p * un
            + pstar * SM
        ) / np.where(
            np.abs(S - SM) > 1.0e-30,
            S - SM,
            np.sign(S - SM + 1.0e-300) * 1.0e-30,
        )
        return Ustar

    UstarL = star_state(UL, rhoL, unL, utL, pL, SL)
    UstarR = star_state(UR, rhoR, unR, utR, pR, SR)

    FstarL = FL + SL[..., None] * (UstarL - UL)
    FstarR = FR + SR[..., None] * (UstarR - UR)

    FHLLC = np.empty_like(UL)
    mask_L = SL >= 0.0
    mask_star_L = (SL < 0.0) & (SM >= 0.0)
    mask_star_R = (SM < 0.0) & (SR > 0.0)
    mask_R = SR <= 0.0

    FHLLC[mask_L] = FL[mask_L]
    FHLLC[mask_star_L] = FstarL[mask_star_L]
    FHLLC[mask_star_R] = FstarR[mask_star_R]
    FHLLC[mask_R] = FR[mask_R]

    return FHLLC


def hllc_flux_x(UL, UR):
    return _hllc_flux_normal(UL, UR, direction="x")


def hllc_flux_y(UL, UR):
    return _hllc_flux_normal(UL, UR, direction="y")

# =============================================================================
# PLM reconstruction implementation (Modified from RK4_PLM.py)
# =============================================================================
def reconstruct_x(U):
    W = conserved_to_primitive(U)
    WL = np.zeros_like(W)
    WR = np.zeros_like(W)

    # Slopes using central/forward/backward differences
    dqL = W[1:-1, :, :] - W[:-2, :, :]
    dqR = W[2:, :, :] - W[1:-1, :, :]

    # van Leer limiter
    slope_LR = dqL * dqR
    slope_limited = np.where(slope_LR > 0.0, 2.0 * slope_LR / (dqL + dqR), 0.0)

    # Calculate values at boundaries of each cell
    WL[1:-1, :, :] = W[1:-1, :, :] - 0.5 * slope_limited
    WR[1:-1, :, :] = W[1:-1, :, :] + 0.5 * slope_limited

    # Boundary copy for ghost zones to maintain zero derivative
    WL[0, :, :] = W[0, :, :]
    WR[0, :, :] = W[0, :, :]
    WL[-1, :, :] = W[-1, :, :]
    WR[-1, :, :] = W[-1, :, :]

    # Apply physical floors
    WL[..., 0] = np.maximum(WL[..., 0], rho_floor)
    WR[..., 0] = np.maximum(WR[..., 0], rho_floor)
    WL[..., 3] = np.maximum(WL[..., 3], P_floor)
    WR[..., 3] = np.maximum(WR[..., 3], P_floor)

    # Return as states on the x-interfaces. 
    # Note: WL contains the left-cell right-face states, WR contains right-cell left-face states.
    # To match Final.py's HLLC logic format, we slice from 0 to Nx-1.
    return primitive_to_conserved(WL[:-1, :, :]), primitive_to_conserved(WR[1:, :, :])


def reconstruct_y(U):
    W = conserved_to_primitive(U)
    WL = np.zeros_like(W)
    WR = np.zeros_like(W)

    # Slopes using central/forward/backward differences
    dqL = W[:, 1:-1, :] - W[:, :-2, :]
    dqR = W[:, 2:, :] - W[:, 1:-1, :]

    # van Leer limiter
    slope_LR = dqL * dqR
    slope_limited = np.where(slope_LR > 0.0, 2.0 * slope_LR / (dqL + dqR), 0.0)

    # Calculate values at boundaries of each cell
    WL[:, 1:-1, :] = W[:, 1:-1, :] - 0.5 * slope_limited
    WR[:, 1:-1, :] = W[:, 1:-1, :] + 0.5 * slope_limited

    # Boundary copy for ghost zones to maintain zero derivative
    WL[:, 0, :] = W[:, 0, :]
    WR[:, 0, :] = W[:, 0, :]
    WL[:, -1, :] = W[:, -1, :]
    WR[:, -1, :] = W[:, -1, :]

    # Apply physical floors
    WL[..., 0] = np.maximum(WL[..., 0], rho_floor)
    WR[..., 0] = np.maximum(WR[..., 0], rho_floor)
    WL[..., 3] = np.maximum(WL[..., 3], P_floor)
    WR[..., 3] = np.maximum(WR[..., 3], P_floor)

    # Return as states on the y-interfaces.
    return primitive_to_conserved(WL[:, :-1, :]), primitive_to_conserved(WR[:, 1:, :])

# =============================================================================
# Optional self-gravity
# =============================================================================
def gravity_potential_fft_periodic(rho_real):
    rho_contrast = rho_real - np.mean(rho_real)
    rho_k = np.fft.fftn(rho_contrast)

    kx = 2.0 * np.pi * np.fft.fftfreq(Nx_In, d=dx)
    ky = 2.0 * np.pi * np.fft.fftfreq(Ny_In, d=dy)
    KX, KY = np.meshgrid(kx, ky, indexing="ij")
    k2 = KX*KX + KY*KY

    phi_k = np.zeros_like(rho_k, dtype=complex)
    mask = k2 > 0.0
    phi_k[mask] = -4.0 * np.pi * Ggrav * rho_k[mask] / k2[mask]

    phi = np.real(np.fft.ifftn(phi_k))
    return phi

def gravity_acceleration_fft_periodic(rho_real):
    rho_contrast = rho_real - np.mean(rho_real)
    rho_k = np.fft.fftn(rho_contrast)
    kx = 2.0 * np.pi * np.fft.fftfreq(Nx_In, d=dx)
    ky = 2.0 * np.pi * np.fft.fftfreq(Ny_In, d=dy)
    KX, KY = np.meshgrid(kx, ky, indexing="ij")
    k2 = KX*KX + KY*KY

    phi_k = np.zeros_like(rho_k, dtype=complex)
    mask = k2 > 0.0
    phi_k[mask] = -4.0 * np.pi * Ggrav * rho_k[mask] / k2[mask]

    gx = np.real(np.fft.ifftn(-1j * KX * phi_k))
    gy = np.real(np.fft.ifftn(-1j * KY * phi_k))
    return gx, gy


def gravity_source(U):
    S = np.zeros_like(U)
    if not USE_SELF_GRAVITY:
        return S

    rho_real = U[nghost:-nghost, nghost:-nghost, 0]
    gx, gy = gravity_acceleration_fft_periodic(rho_real)

    rho = U[nghost:-nghost, nghost:-nghost, 0]
    u = U[nghost:-nghost, nghost:-nghost, 1] / np.maximum(rho, rho_floor)
    v = U[nghost:-nghost, nghost:-nghost, 2] / np.maximum(rho, rho_floor)

    S[nghost:-nghost, nghost:-nghost, 1] = rho * gx
    S[nghost:-nghost, nghost:-nghost, 2] = rho * gy
    S[nghost:-nghost, nghost:-nghost, 3] = rho * (u * gx + v * gy)
    return S

# =============================================================================
# RHS and RK4 update
# =============================================================================
def compute_rhs(U):
    Uwork = U.copy()
    Uwork = apply_floors(Uwork)
    apply_periodic_boundary(Uwork)

    if SOLVER == 'Rusanov':
        # Upgrade to 2nd-order scheme by using PLM data reconstruction for Rusanov solver
        ULx, URx = reconstruct_x(Uwork)
        Fx = rusanov_flux_x(ULx, URx)

        ULy, URy = reconstruct_y(Uwork)
        Gy = rusanov_flux_y(ULy, URy)
    else:
        # Default HLLC solver using PLM reconstruction
        ULx, URx = reconstruct_x(Uwork)
        Fx = hllc_flux_x(ULx, URx)

        ULy, URy = reconstruct_y(Uwork)
        Gy = hllc_flux_y(ULy, URy)

    rhs = np.zeros_like(Uwork)
    i0, i1 = nghost, Nx - nghost
    j0, j1 = nghost, Ny - nghost

    rhs[i0:i1, j0:j1, :] = (
        -(Fx[i0:i1, j0:j1, :] - Fx[i0-1:i1-1, j0:j1, :]) / dx
        -(Gy[i0:i1, j0:j1, :] - Gy[i0:i1, j0-1:j1-1, :]) / dy
    )

    rhs += gravity_source(Uwork)
    return rhs


def rk4_step(U, dt):
    k1 = compute_rhs(U)

    U2 = apply_floors(U + 0.5 * dt * k1)
    apply_periodic_boundary(U2)
    k2 = compute_rhs(U2)

    U3 = apply_floors(U + 0.5 * dt * k2)
    apply_periodic_boundary(U3)
    k3 = compute_rhs(U3)

    U4 = apply_floors(U + dt * k3)
    apply_periodic_boundary(U4)
    k4 = compute_rhs(U4)

    Unew = U + (dt / 6.0) * (k1 + 2.0*k2 + 2.0*k3 + k4)
    Unew = apply_floors(Unew)
    apply_periodic_boundary(Unew)
    return Unew


def compute_timestep(U, t):
    W = conserved_to_primitive(U)
    rho = W[nghost:-nghost, nghost:-nghost, 0]
    u = W[nghost:-nghost, nghost:-nghost, 1]
    v = W[nghost:-nghost, nghost:-nghost, 2]
    P = W[nghost:-nghost, nghost:-nghost, 3]

    cs = np.sqrt(gamma * P / rho)
    max_speed = np.max(np.maximum(np.abs(u) + cs, np.abs(v) + cs))
    
    dt_hydro = cfl * min(dx, dy) / max(max_speed, 1.0e-30)
    dt = dt_hydro

    if USE_SELF_GRAVITY:
        rho_real = U[nghost:-nghost, nghost:-nghost, 0]
        gx, gy = gravity_acceleration_fft_periodic(rho_real)
        gmax = np.max(np.sqrt(gx*gx + gy*gy))

        if gmax > 1.0e-30:
            dt_grav = np.sqrt(cfl * min(dx, dy) / gmax)
            dt = min(dt, dt_grav)

    return min(dt, end_time - t)

# =============================================================================
# Initial condition and diagnostics
# =============================================================================
def set_initial_condition():
    W = np.zeros((Nx, Ny, 4))
    W[..., 0] = rho0
    W[..., 1] = 0.0
    W[..., 2] = 0.0
    W[..., 3] = P_amb

    # Deposit total energy E0 as thermal energy inside r_blast.
    # In 2D, this is energy per unit length; area = pi*r_blast^2.
    blast_mask = R_real < r_blast
    blast_area = np.sum(blast_mask) * dx * dy
    P_blast_add = (gamma - 1.0) * E0 / blast_area

    W_real = W[nghost:-nghost, nghost:-nghost, :]
    W_real[blast_mask, 3] += P_blast_add
    W[nghost:-nghost, nghost:-nghost, :] = W_real

    U = primitive_to_conserved(W)
    apply_periodic_boundary(U)
    return U


def estimate_shock_radius(U, threshold=1.1):
    rho = U[nghost:-nghost, nghost:-nghost, 0]
    mask = rho > threshold * rho0
    if not np.any(mask):
        return 0.0
    return np.max(R_real[mask])


def sedov_radius_2d(t, xi=1.0):
    if t <= 0.0:
        return 0.0
    return xi * (E0 * t*t / rho0)**0.25


def radial_profile(quantity, nbins=80):
    r = R_real.ravel()
    q = quantity.ravel()
    bins = np.linspace(0.0, np.max(r), nbins+1)
    rc = 0.5 * (bins[:-1] + bins[1:])
    prof = np.zeros(nbins)
    for k in range(nbins):
        m = (r >= bins[k]) & (r < bins[k+1])
        prof[k] = np.mean(q[m]) if np.any(m) else np.nan
    return rc, prof


def compute_thermal_energy(U):
    W = conserved_to_primitive(U)
    P = W[nghost:-nghost, nghost:-nghost, 3]
    return np.sum(P / (gamma - 1.0)) * dx * dy


def compute_kinetic_energy(U):
    W = conserved_to_primitive(U)
    rho = W[nghost:-nghost, nghost:-nghost, 0]
    u = W[nghost:-nghost, nghost:-nghost, 1]
    v = W[nghost:-nghost, nghost:-nghost, 2]
    return np.sum(0.5 * rho * (u*u + v*v)) * dx * dy


def compute_hydro_energy(U):
    E = U[nghost:-nghost, nghost:-nghost, 3]
    return np.sum(E) * dx * dy


def compute_gravitational_energy(U):
    if not USE_SELF_GRAVITY:
        return 0.0
    rho = U[nghost:-nghost, nghost:-nghost, 0]
    rho_contrast = rho - np.mean(rho)
    phi = gravity_potential_fft_periodic(rho)
    return 0.5 * np.sum(rho_contrast * phi) * dx * dy

# =============================================================================
# Main run
# =============================================================================
def main():
    # output direction
    current_time_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_dir = os.path.join(".", "Final_test_data", SOLVER, current_time_str)
    frames_dir = os.path.join(output_dir, "gif_frames")
    
    os.makedirs(frames_dir, exist_ok=True)
    print(f"Data will be saved in {output_dir}")

    init_txt_path = os.path.join(output_dir, "initial_conditions.txt")
    with open(init_txt_path, "w", encoding="utf-8") as f:
        f.write("=============================================================================\n")
        f.write(" SIMULATION INITIAL CONDITIONS & PARAMETERS\n")
        f.write("=============================================================================\n\n")
        
        f.write("# ---- Grid & Domain ----\n")
        f.write(f"Lx              = {Lx}\n")
        f.write(f"Ly              = {Ly}\n")
        f.write(f"Nx_In           = {Nx_In}\n")
        f.write(f"Ny_In           = {Ny_In}\n")
        f.write(f"nghost          = {nghost}\n\n")
        
        f.write("# ---- Numerics & Time ----\n")
        f.write(f"gamma           = {gamma:.6f}\n")
        f.write(f"cfl             = {cfl}\n")
        f.write(f"end_time        = {end_time}\n")
        f.write(f"output_interval = {output_interval}\n\n")
        
        f.write("# ---- Sedov Blast Wave ----\n")
        f.write(f"rho0            = {rho0}       # uniform ambient pre-shock density\n")
        f.write(f"P_amb           = {P_amb:.1e}  # ambient pressure\n")
        f.write(f"E0              = {E0}       # injected thermal energy per unit length in 2D\n")
        f.write(f"r_blast         = {r_blast}     # radius of central energy injection region\n\n")
        
        f.write("# ---- Self-Gravity ----\n")
        f.write(f"USE_SELF_GRAVITY= {USE_SELF_GRAVITY}\n")
        f.write(f"Ggrav           = {Ggrav}       # gravitational constant\n\n")
        
        f.write("# ---- Riemann Solver ----\n")
        f.write(f"SOLVER          = {SOLVER}\n\n")
        
        f.write("# ---- Numerical Floors ----\n")
        f.write(f"rho_floor       = {rho_floor:.1e}\n")
        f.write(f"P_floor         = {P_floor:.1e}\n\n")
        
        f.write("# ---- Derived Grid Constants ----\n")
        f.write(f"Nx              = {Nx}\n")
        f.write(f"Ny              = {Ny}\n")
        f.write(f"dx              = {dx:.6e}\n")
        f.write(f"dy              = {dy:.6e}\n")

    U = set_initial_condition()
    t = 0.0
    next_output = 0.0

    frames = []
    times = []
    shock_radii = []
    sedov_radii = []
    energy_times = []
    thermal_hist = []
    kinetic_hist = []
    hydro_hist = []
    grav_hist = []
    total_hist = []
    
    while t < end_time - 1.0e-14:
        dt = compute_timestep(U, t)
        U = rk4_step(U, dt)
        t += dt

        if t >= next_output or t >= end_time - 1.0e-14:
            rho = U[nghost:-nghost, nghost:-nghost, 0].copy()
            frames.append(rho)
            times.append(t)
            shock_radii.append(estimate_shock_radius(U))
            sedov_radii.append(sedov_radius_2d(t))

            Etherm = compute_thermal_energy(U)
            Ekin = compute_kinetic_energy(U)
            Ehydro = compute_hydro_energy(U)
            Egrav = compute_gravitational_energy(U)
            Etot = Ehydro + Egrav
            energy_times.append(t)
            thermal_hist.append(Etherm)
            kinetic_hist.append(Ekin)
            hydro_hist.append(Ehydro)
            grav_hist.append(Egrav)
            total_hist.append(Etot)

            print(
                f"t={t:.5f}, dt={dt:.3e}, "
                f"R_shock={shock_radii[-1]:.4f}, "
                f"R_sedov~{sedov_radii[-1]:.4f}, "
                f"Etot={Etot:.6e}"
            )

            next_output += output_interval

    # Save shock radius diagnostic
    np.savetxt(
        os.path.join(output_dir, "shock_radius_diagnostic.txt"),
        np.column_stack([times, shock_radii, sedov_radii]),
        header="time  measured_R_shock  Sedov_R_2D_xi_equals_1"
    )
    
    energy_times = np.array(energy_times)
    thermal_hist = np.array(thermal_hist)
    kinetic_hist = np.array(kinetic_hist)
    hydro_hist = np.array(hydro_hist)
    grav_hist = np.array(grav_hist)
    total_hist = np.array(total_hist)
    
    np.savetxt(
        os.path.join(output_dir, "energy_diagnostic.txt"),
        np.column_stack([
            energy_times,
            thermal_hist,
            kinetic_hist,
            hydro_hist,
            grav_hist,
            total_hist
        ]),
        header="time thermal kinetic hydro gravitational total"
    )

    plt.figure(figsize=(7, 5))
    plt.plot(energy_times, total_hist, label="Total = Hydro + Gravity")
    plt.plot(energy_times, hydro_hist, label="Hydro")
    plt.plot(energy_times, grav_hist, label="Gravitational")
    plt.xlabel("t")
    plt.ylabel("Energy")
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, "energy_total_hydro_gravity.png"), dpi=180)
    plt.close()

    plt.figure(figsize=(7, 5))
    plt.plot(energy_times, thermal_hist, label="Thermal")
    plt.plot(energy_times, kinetic_hist, label="Kinetic")
    plt.xlabel("t")
    plt.ylabel("Energy")
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, "energy_thermal_kinetic.png"), dpi=180)
    plt.close()

    energy_error = (total_hist - total_hist[0]) / abs(total_hist[0])
    plt.figure(figsize=(7, 5))
    plt.plot(energy_times, energy_error)
    plt.xlabel("t")
    plt.ylabel("(E_total(t) - E_total(0)) / |E_total(0)|")
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, "energy_total_relative_error.png"), dpi=180)
    plt.close()

    # Plot final radial density profile
    rc, rho_prof = radial_profile(frames[-1])
    plt.figure(figsize=(6, 4))
    plt.plot(rc, rho_prof)
    plt.xlabel("r")
    plt.ylabel("azimuthally averaged density")
    plt.title("Final radial density profile")
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, "final_density_radial_profile.png"), dpi=180)
    plt.close()

    # Plot final density contrast, which is the actual Poisson source.
    final_rho = frames[-1]
    delta_rho = final_rho - np.mean(final_rho)
    plt.figure(figsize=(6, 5))
    plt.imshow(
        delta_rho.T,
        origin="lower",
        extent=[-0.5*Lx, 0.5*Lx, -0.5*Ly, 0.5*Ly],
        interpolation="nearest"
    )
    plt.colorbar(label="density contrast, rho - mean(rho)")
    plt.xlabel("x")
    plt.ylabel("y")
    plt.title("Final Poisson source: density contrast")
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, "final_density_contrast_poisson_source.png"), dpi=180)
    plt.close()

    # Density animation & frame export
    fig, ax = plt.subplots(figsize=(6, 5))
    im = ax.imshow(
        frames[0].T,
        origin="lower",
        extent=[-0.5*Lx, 0.5*Lx, -0.5*Ly, 0.5*Ly],
        interpolation="nearest"
    )
    cb = plt.colorbar(im, ax=ax)
    cb.set_label("density")
    title = ax.set_title("")
    ax.set_xlabel("x")
    ax.set_ylabel("y")

    def update_frame(n):
        im.set_data(frames[n].T)
        im.set_clim(np.min(frames[n]), np.max(frames[n]))
        # im.set_clim(0, 3.5)
        title.set_text(f"Sedov-like blast + self-gravity ({SOLVER}), t={times[n]:.4f}")
        
        # save gif frames
        frame_filename = os.path.join(frames_dir, f"{n:02d}.png")
        plt.savefig(frame_filename, dpi=150)
        
        return im, title

    anim = FuncAnimation(fig, update_frame, frames=len(frames), interval=80, blit=False)
    anim.save(os.path.join(output_dir, f"sedov_selfgravity_RK4_PLM_{SOLVER}_density.gif"), writer=PillowWriter(fps=12))
    plt.close(fig)

    print(f"Data have been saved in {output_dir}")
    print("Saved: energy_diagnostic.txt")
    print("Saved: energy_total_hydro_gravity.png")
    print("Saved: energy_thermal_kinetic.png")
    print("Saved: energy_total_relative_error.png")
    print(f"Saved: sedov_selfgravity_RK4_PLM_{SOLVER}_density.gif")
    print("Saved: final_density_radial_profile.png")
    print("Saved: final_density_contrast_poisson_source.png")
    print("Saved: shock_radius_diagnostic.txt")


if __name__ == "__main__":
    main()