# =============================================================================
# 2D Sedov-like blast wave with gas self-gravity feedback
# =============================================================================
# Physics:
#   Conserved variables U = [rho, rho*u, rho*v, E]
#   Euler equations with optional gravitational source terms:
#       dU/dt + dF/dx + dG/dy = S_grav
#
# Numerical method:
#   Time integration        : RK4
#   Spatial reconstruction  : PPM-like reconstruction on primitive variables
#   Interface flux          : Rusanov / local Lax-Friedrichs flux
#   Boundary condition      : outflow for hydrodynamics
#   Gravity                 : periodic FFT Poisson solver sourced by rho-rho_mean
#
# Important modeling choice:
#   This is a Sedov-like setup: the shock is generated by central ENERGY
#   injection, not by imposing the shock radius by hand.
#   The Sedov-Taylor radius is used only as a diagnostic/reference:
#       R_s(t) ~ xi * (E0*t^2/rho0)^(1/(d+2))
#   In 2D: R_s(t) ~ xi * (E0*t^2/rho0)^(1/4)
# =============================================================================

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, PillowWriter

# =============================================================================
# Parameters
# =============================================================================
Lx = 1.0
Ly = 1.0
Nx_In = 128
Ny_In = 128
nghost = 3

gamma = 5.0 / 3.0
cfl = 0.35
end_time = 0.2
## critical 0.15
output_interval = 0.0025

# Sedov-like initial condition
rho0 = 1.0         # uniform ambient pre-shock density
P_amb = 1.0e-5      # ambient pressure
E0 = 1.0            # injected thermal energy per unit length in 2D
r_blast = 0.03      # radius of central energy injection region

# Self-gravity switch
# True means shock-compressed density sources Phi through Poisson equation.
USE_SELF_GRAVITY = True
Ggrav = 500.0        # gravitational constant in code units; increase carefully

# Numerical floors
rho_floor = 1.0e-12
P_floor = 1.0e-12

# Derived grid constants
Nx = Nx_In + 2 * nghost
Ny = Ny_In + 2 * nghost
dx = Lx / Nx_In
dy = Ly / Ny_In

x_real = (np.arange(Nx_In) + 0.5) * dx - 0.5 * Lx
y_real = (np.arange(Ny_In) + 0.5) * dy - 0.5 * Ly
X_real, Y_real = np.meshgrid(x_real, y_real, indexing="ij")
R_real = np.sqrt(X_real**2 + Y_real**2)

# =============================================================================
# Basic variable conversion
# =============================================================================
def compute_pressure(U):
    rho = np.maximum(U[..., 0], rho_floor)
    mx = U[..., 1]
    my = U[..., 2]
    E = U[..., 3]
    kinetic = 0.5 * (mx**2 + my**2) / rho
    P = (gamma - 1.0) * (E - kinetic)
    return np.maximum(P, P_floor)


def conserved_to_primitive(U):
    W = np.empty_like(U)
    rho = np.maximum(U[..., 0], rho_floor)
    P = compute_pressure(U)
    W[..., 0] = rho
    W[..., 1] = U[..., 1] / rho
    W[..., 2] = U[..., 2] / rho
    W[..., 3] = P
    return W


def primitive_to_conserved(W):
    U = np.empty_like(W)
    rho = np.maximum(W[..., 0], rho_floor)
    u = W[..., 1]
    v = W[..., 2]
    P = np.maximum(W[..., 3], P_floor)
    U[..., 0] = rho
    U[..., 1] = rho * u
    U[..., 2] = rho * v
    U[..., 3] = P / (gamma - 1.0) + 0.5 * rho * (u*u + v*v)
    return U


def apply_floors(U):
    U[..., 0] = np.maximum(U[..., 0], rho_floor)
    W = conserved_to_primitive(U)
    W[..., 0] = np.maximum(W[..., 0], rho_floor)
    W[..., 3] = np.maximum(W[..., 3], P_floor)
    return primitive_to_conserved(W)

# =============================================================================
# Boundary condition
# =============================================================================
def apply_outflow_boundary(U):
    U[:nghost, :, :] = U[nghost:nghost+1, :, :]
    U[Nx-nghost:, :, :] = U[Nx-nghost-1:Nx-nghost, :, :]
    U[:, :nghost, :] = U[:, nghost:nghost+1, :]
    U[:, Ny-nghost:, :] = U[:, Ny-nghost-1:Ny-nghost, :]

# =============================================================================
# Fluxes
# =============================================================================
def flux_x(U):
    W = conserved_to_primitive(U)
    rho, u, v, P = W[..., 0], W[..., 1], W[..., 2], W[..., 3]
    F = np.empty_like(U)
    F[..., 0] = rho * u
    F[..., 1] = rho * u*u + P
    F[..., 2] = rho * u*v
    F[..., 3] = (U[..., 3] + P) * u
    return F


def flux_y(U):
    W = conserved_to_primitive(U)
    rho, u, v, P = W[..., 0], W[..., 1], W[..., 2], W[..., 3]
    G = np.empty_like(U)
    G[..., 0] = rho * v
    G[..., 1] = rho * u*v
    G[..., 2] = rho * v*v + P
    G[..., 3] = (U[..., 3] + P) * v
    return G


def rusanov_flux_x(UL, UR):
    WL = conserved_to_primitive(UL)
    WR = conserved_to_primitive(UR)
    cL = np.sqrt(gamma * WL[..., 3] / WL[..., 0])
    cR = np.sqrt(gamma * WR[..., 3] / WR[..., 0])
    a = np.maximum(np.abs(WL[..., 1]) + cL, np.abs(WR[..., 1]) + cR)
    return 0.5 * (flux_x(UL) + flux_x(UR)) - 0.5 * a[..., None] * (UR - UL)


def rusanov_flux_y(UL, UR):
    WL = conserved_to_primitive(UL)
    WR = conserved_to_primitive(UR)
    cL = np.sqrt(gamma * WL[..., 3] / WL[..., 0])
    cR = np.sqrt(gamma * WR[..., 3] / WR[..., 0])
    a = np.maximum(np.abs(WL[..., 2]) + cL, np.abs(WR[..., 2]) + cR)
    return 0.5 * (flux_y(UL) + flux_y(UR)) - 0.5 * a[..., None] * (UR - UL)

# =============================================================================
# PPM-like reconstruction
# =============================================================================
def minmod(a, b):
    return 0.5 * (np.sign(a) + np.sign(b)) * np.minimum(np.abs(a), np.abs(b))


def ppm_reconstruct_1d(q):
    """Return left/right interface states for a 1D array q.

    qL_face[i] and qR_face[i] are states at interface i+1/2 from the left
    cell i and the right cell i+1, respectively.
    """
    n = q.size
    slope = np.zeros(n)
    slope[1:-1] = minmod(q[1:-1] - q[:-2], q[2:] - q[1:-1])

    qL_cell = q - 0.5 * slope
    qR_cell = q + 0.5 * slope

    # Monotonicity limiter
    qmin = np.minimum(q[:-1], q[1:])
    qmax = np.maximum(q[:-1], q[1:])
    left_state = np.clip(qR_cell[:-1], qmin, qmax)
    right_state = np.clip(qL_cell[1:], qmin, qmax)
    return left_state, right_state


def reconstruct_x(U):
    W = conserved_to_primitive(U)
    WL = np.zeros((Nx-1, Ny, 4))
    WR = np.zeros((Nx-1, Ny, 4))
    for j in range(Ny):
        for m in range(4):
            WL[:, j, m], WR[:, j, m] = ppm_reconstruct_1d(W[:, j, m])
    return primitive_to_conserved(WL), primitive_to_conserved(WR)


def reconstruct_y(U):
    W = conserved_to_primitive(U)
    WL = np.zeros((Nx, Ny-1, 4))
    WR = np.zeros((Nx, Ny-1, 4))
    for i in range(Nx):
        for m in range(4):
            WL[i, :, m], WR[i, :, m] = ppm_reconstruct_1d(W[i, :, m])
    return primitive_to_conserved(WL), primitive_to_conserved(WR)

# =============================================================================
# Optional self-gravity
# =============================================================================
def gravity_acceleration_fft_periodic(rho_real):
    """Periodic FFT Poisson solver using density contrast rho-rho_mean.

    This is a simple template. For an isolated cloud, an isolated-boundary
    Poisson solver would be more physical than this periodic solver.
    """
    rho_contrast = rho_real - np.mean(rho_real)
    rho_k = np.fft.fftn(rho_contrast)

    kx = 2.0 * np.pi * np.fft.fftfreq(Nx_In, d=dx)
    ky = 2.0 * np.pi * np.fft.fftfreq(Ny_In, d=dy)
    KX, KY = np.meshgrid(kx, ky, indexing="ij")
    k2 = KX*KX + KY*KY

    phi_k = np.zeros_like(rho_k, dtype=complex)
    mask = k2 > 0.0
    phi_k[mask] = -4.0 * np.pi * Ggrav * rho_k[mask] / k2[mask]

    gx = np.real(np.fft.ifftn(-1j * KX * phi_k))
    gy = np.real(np.fft.ifftn(-1j * KY * phi_k))
    return gx, gy


def gravity_source(U):
    S = np.zeros_like(U)
    if not USE_SELF_GRAVITY:
        return S

    rho_real = U[nghost:-nghost, nghost:-nghost, 0]
    gx, gy = gravity_acceleration_fft_periodic(rho_real)

    rho = U[nghost:-nghost, nghost:-nghost, 0]
    u = U[nghost:-nghost, nghost:-nghost, 1] / np.maximum(rho, rho_floor)
    v = U[nghost:-nghost, nghost:-nghost, 2] / np.maximum(rho, rho_floor)

    S[nghost:-nghost, nghost:-nghost, 1] = rho * gx
    S[nghost:-nghost, nghost:-nghost, 2] = rho * gy
    S[nghost:-nghost, nghost:-nghost, 3] = rho * (u * gx + v * gy)
    return S

# =============================================================================
# RHS and RK4 update
# =============================================================================
def compute_rhs(U):
    Uwork = U.copy()
    Uwork = apply_floors(Uwork)
    apply_outflow_boundary(Uwork)

    ULx, URx = reconstruct_x(Uwork)
    Fx = rusanov_flux_x(ULx, URx)

    ULy, URy = reconstruct_y(Uwork)
    Gy = rusanov_flux_y(ULy, URy)

    rhs = np.zeros_like(Uwork)
    i0, i1 = nghost, Nx - nghost
    j0, j1 = nghost, Ny - nghost

    rhs[i0:i1, j0:j1, :] = (
        -(Fx[i0:i1, j0:j1, :] - Fx[i0-1:i1-1, j0:j1, :]) / dx
        -(Gy[i0:i1, j0:j1, :] - Gy[i0:i1, j0-1:j1-1, :]) / dy
    )

    rhs += gravity_source(Uwork)
    return rhs


def rk4_step(U, dt):
    k1 = compute_rhs(U)
    k2 = compute_rhs(apply_floors(U + 0.5 * dt * k1))
    k3 = compute_rhs(apply_floors(U + 0.5 * dt * k2))
    k4 = compute_rhs(apply_floors(U + dt * k3))
    Unew = U + (dt / 6.0) * (k1 + 2.0*k2 + 2.0*k3 + k4)
    Unew = apply_floors(Unew)
    apply_outflow_boundary(Unew)
    return Unew


def compute_timestep(U, t):
    W = conserved_to_primitive(U)
    rho = W[nghost:-nghost, nghost:-nghost, 0]
    u = W[nghost:-nghost, nghost:-nghost, 1]
    v = W[nghost:-nghost, nghost:-nghost, 2]
    P = W[nghost:-nghost, nghost:-nghost, 3]
    cs = np.sqrt(gamma * P / rho)
    max_speed = np.max(np.maximum(np.abs(u) + cs, np.abs(v) + cs))
    dt = cfl * min(dx, dy) / max(max_speed, 1.0e-30)
    return min(dt, end_time - t)

# =============================================================================
# Initial condition and diagnostics
# =============================================================================
def set_initial_condition():
    W = np.zeros((Nx, Ny, 4))
    W[..., 0] = rho0
    W[..., 1] = 0.0
    W[..., 2] = 0.0
    W[..., 3] = P_amb

    # Deposit total energy E0 as thermal energy inside r_blast.
    # In 2D, this is energy per unit length; area = pi*r_blast^2.
    blast_mask = R_real < r_blast
    blast_area = np.sum(blast_mask) * dx * dy
    P_blast_add = (gamma - 1.0) * E0 / blast_area

    W_real = W[nghost:-nghost, nghost:-nghost, :]
    W_real[blast_mask, 3] += P_blast_add
    W[nghost:-nghost, nghost:-nghost, :] = W_real

    U = primitive_to_conserved(W)
    apply_outflow_boundary(U)
    return U


def estimate_shock_radius(U, threshold=1.1):
    """Estimate shock radius from a density enhancement threshold.

    The default threshold is mild because Rusanov flux spreads shocks.
    This diagnostic does not affect the evolution.
    """
    rho = U[nghost:-nghost, nghost:-nghost, 0]
    mask = rho > threshold * rho0
    if not np.any(mask):
        return 0.0
    return np.max(R_real[mask])


def sedov_radius_2d(t, xi=1.0):
    if t <= 0.0:
        return 0.0
    return xi * (E0 * t*t / rho0)**0.25


def radial_profile(quantity, nbins=80):
    r = R_real.ravel()
    q = quantity.ravel()
    bins = np.linspace(0.0, np.max(r), nbins+1)
    rc = 0.5 * (bins[:-1] + bins[1:])
    prof = np.zeros(nbins)
    for k in range(nbins):
        m = (r >= bins[k]) & (r < bins[k+1])
        prof[k] = np.mean(q[m]) if np.any(m) else np.nan
    return rc, prof

# =============================================================================
# Main run
# =============================================================================
def main():
    U = set_initial_condition()
    t = 0.0
    next_output = 0.0

    frames = []
    times = []
    shock_radii = []
    sedov_radii = []

    while t < end_time - 1.0e-14:
        dt = compute_timestep(U, t)
        U = rk4_step(U, dt)
        t += dt

        if t >= next_output or t >= end_time - 1.0e-14:
            rho = U[nghost:-nghost, nghost:-nghost, 0].copy()
            frames.append(rho)
            times.append(t)
            shock_radii.append(estimate_shock_radius(U))
            sedov_radii.append(sedov_radius_2d(t))
            print(f"t={t:.5f}, dt={dt:.3e}, R_shock={shock_radii[-1]:.4f}, R_sedov~{sedov_radii[-1]:.4f}")
            next_output += output_interval

    # Save shock radius diagnostic
    np.savetxt(
        "shock_radius_diagnostic.txt",
        np.column_stack([times, shock_radii, sedov_radii]),
        header="time  measured_R_shock  Sedov_R_2D_xi_equals_1"
    )

    # Plot final radial density profile
    rc, rho_prof = radial_profile(frames[-1])
    plt.figure(figsize=(6, 4))
    plt.plot(rc, rho_prof)
    plt.xlabel("r")
    plt.ylabel("azimuthally averaged density")
    plt.title("Final radial density profile")
    plt.tight_layout()
    plt.savefig("final_density_radial_profile.png", dpi=180)
    plt.close()

    # Plot final density contrast, which is the actual Poisson source.
    final_rho = frames[-1]
    delta_rho = final_rho - np.mean(final_rho)
    plt.figure(figsize=(6, 5))
    plt.imshow(
        delta_rho.T,
        origin="lower",
        extent=[-0.5*Lx, 0.5*Lx, -0.5*Ly, 0.5*Ly],
        interpolation="nearest"
    )
    plt.colorbar(label="density contrast, rho - mean(rho)")
    plt.xlabel("x")
    plt.ylabel("y")
    plt.title("Final Poisson source: density contrast")
    plt.tight_layout()
    plt.savefig("final_density_contrast_poisson_source.png", dpi=180)
    plt.close()

    # Density animation
    fig, ax = plt.subplots(figsize=(6, 5))
    im = ax.imshow(
        frames[0].T,
        origin="lower",
        extent=[-0.5*Lx, 0.5*Lx, -0.5*Ly, 0.5*Ly],
        interpolation="nearest"
    )
    cb = plt.colorbar(im, ax=ax)
    cb.set_label("density")
    title = ax.set_title("")
    ax.set_xlabel("x")
    ax.set_ylabel("y")

    def update_frame(n):
        im.set_data(frames[n].T)
        im.set_clim(np.min(frames[n]), np.max(frames[n]))
        title.set_text(f"Sedov-like blast + self-gravity, t={times[n]:.4f}")
        return im, title

    anim = FuncAnimation(fig, update_frame, frames=len(frames), interval=80, blit=False)
    anim.save("sedov_selfgravity_RK4_PPM_density.gif", writer=PillowWriter(fps=12))
    plt.close(fig)

    print("Saved: sedov_selfgravity_RK4_PPM_density.gif")
    print("Saved: final_density_radial_profile.png")
    print("Saved: final_density_contrast_poisson_source.png")
    print("Saved: shock_radius_diagnostic.txt")


if __name__ == "__main__":
    main()
